server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_hotel
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8085